Improved base Nginx Plus configuration, docs, bash scripts, and the Postman collection.
Signed-off-by: Exadra37 <exadra37@gmail.com>

diff --git a/bin/install-approov b/bin/install-approov
--- a/bin/install-approov
+++ b/bin/install-approov
@@ -4,6 +4,13 @@ set -eu
 
 Main()
 {
+  if [ ! -f ./etc/nginx/approov-secret.jwk ]; then
+    printf "\n---> FATAL ERROR: Missing file ./etc/nginx/approov-secret.jwk, check README for instructions. <---\n\n"
+    exit 1
+  fi
+
+  cp -b ./etc/nginx/approov-secret.jwk /etc/nginx/approov-secret.jwk
+
   for input in "${@}"; do
     case "${input}" in
       --with-nginx-conf )
